# Generated by Django 5.2.17 on 2026-09-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(max_length=8, unique=True)),
                ('suite', models.CharField(default='x25519-sha256-chacha20poly1305', max_length=40)),
                ('public_key', models.CharField(help_text='32 bytes, base64url, unpadded', max_length=64)),
                ('private_key', models.BinaryField(help_text='32 raw bytes. Never leaves the server.')),
                ('not_after', models.DateField(help_text='Last day clients should encrypt to this key.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-not_after', '-key_id'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitSalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(unique=True)),
                ('salt', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateLimitBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(db_index=True, max_length=64)),
                ('scope', models.CharField(max_length=16)),
                ('window_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['window_start'], name='ingest_rate_window__94f171_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'scope', 'window_start'), name='unique_bucket_window')],
            },
        ),
        migrations.CreateModel(
            name='RawObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=32)),
                ('bssid', models.CharField(db_index=True, max_length=17)),
                ('security', models.CharField(max_length=8)),
                ('captive_portal', models.CharField(default='unknown', max_length=8)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('accuracy_m', models.FloatField()),
                ('rssi', models.IntegerField()),
                ('frequency_mhz', models.IntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField()),
                ('source', models.CharField(max_length=10)),
                ('bucket', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['bssid', 'observed_at'], name='ingest_rawo_bssid_4e08f0_idx')],
            },
        ),
    ]
