# Generated by Django 5.2.17 on 2026-09-18 08:27

import django.db.models.deletion
import networks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=networks.models.new_public_id, max_length=12, unique=True)),
                ('ssid', models.CharField(max_length=32)),
                ('security', models.CharField(default='open', max_length=8)),
                ('captive_portal', models.CharField(default='unknown', max_length=8)),
                ('verification', models.CharField(choices=[('community', 'community'), ('owner-verified', 'owner-verified')], default='community', max_length=16)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('cell', models.CharField(blank=True, db_index=True, max_length=7)),
                ('first_seen', models.DateField(blank=True, null=True)),
                ('last_seen', models.DateField(blank=True, null=True)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('weight_sum', models.FloatField(default=0.0)),
                ('weighted_lat_sum', models.FloatField(default=0.0)),
                ('weighted_lon_sum', models.FloatField(default=0.0)),
                ('span_min_lat', models.FloatField(blank=True, null=True)),
                ('span_max_lat', models.FloatField(blank=True, null=True)),
                ('span_min_lon', models.FloatField(blank=True, null=True)),
                ('span_max_lon', models.FloatField(blank=True, null=True)),
                ('is_mobile', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('unpublished_reason', models.CharField(blank=True, max_length=32)),
                ('last_aggregated_at', models.DateTimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=120)),
                ('venue_kind', models.CharField(blank=True, max_length=40)),
                ('publish_credential', models.BooleanField(default=False)),
                ('credential_type', models.CharField(blank=True, max_length=16)),
                ('credential_secret', models.CharField(blank=True, max_length=128)),
                ('credential_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['ssid'],
            },
        ),
        migrations.CreateModel(
            name='RetiredPublicId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=12, unique=True)),
                ('retired_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssid', models.CharField(max_length=32)),
                ('bssids', models.JSONField(blank=True, default=list)),
                ('venue_name', models.CharField(max_length=120)),
                ('venue_kind', models.CharField(blank=True, max_length=40)),
                ('venue_lat', models.FloatField(blank=True, null=True)),
                ('venue_lon', models.FloatField(blank=True, null=True)),
                ('publish_credential', models.BooleanField(default=False)),
                ('credential_type', models.CharField(blank=True, max_length=16)),
                ('credential_secret', models.CharField(blank=True, max_length=128)),
                ('credential_note', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, help_text='Never published.', max_length=254)),
                ('challenge_code', models.CharField(max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('verified', 'verified'), ('rejected', 'rejected'), ('expired', 'expired')], default='pending', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('moderator_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='networks.network')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkBssid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(max_length=17, unique=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bssids', to='networks.network')),
            ],
        ),
        migrations.CreateModel(
            name='OptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid_hmac', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ssid', models.CharField(blank=True, max_length=32)),
                ('cell', models.CharField(blank=True, max_length=5)),
                ('reason', models.CharField(blank=True, choices=[('mine', 'mine'), ('private', 'private'), ('wrong', 'wrong'), ('other', 'other')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ssid', 'cell'], name='networks_op_ssid_d69aa5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('works', 'works'), ('fails', 'fails'), ('not_free', 'not_free'), ('private', 'private'), ('gone', 'gone')], max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('bucket', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderated', models.BooleanField(default=False)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='networks.network')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
